name: group_radio_button
description: Flutter librity to create radio groups and radio button with labels.
version: 1.0.0
homepage: https://github.com/TercyoStorck/group_radio_button
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
